export {
  AppearancePartialSchema,
  BackoffPartialSchema,
  BackoffStrategySchema,
  BACKOFF_STRATEGIES,
  ContextPartialSchema,
  CrabdConfigPartialSchema,
  CustomProviderSchema,
  DEFAULT_CONFIG,
  McpServerSchema,
  ModePartialSchema,
  NpmRegistrySchema,
  RateLimitOnExhaustedSchema,
  RateLimitPartialSchema,
  RateLimitTriggerScopeSchema,
  RATE_LIMIT_ON_EXHAUSTED,
  RATE_LIMIT_TRIGGER_SCOPES,
  ReviewStrictnessSchema,
  REVIEW_STRICTNESS_DEFAULT,
  REVIEW_STRICTNESS_MAX,
  REVIEW_STRICTNESS_MIN,
  ReposPartialSchema,
  SandboxPartialSchema,
  ThinkingLevelSchema,
  THINKING_LEVELS,
  parseConfigObject,
  type AppearancePartial,
  type BackoffPartial,
  type BackoffStrategy,
  type ContextPartial,
  type CrabdConfigPartial,
  type CustomProvider,
  type GovernancePartial,
  type McpServer,
  type LimitsPartial,
  type ModePartial,
  type NpmRegistry,
  type PermissionsPartial,
  type PromptPartial,
  type ProvidersPartial,
  type RateLimitOnExhausted,
  type RateLimitPartial,
  type RateLimitTriggerScope,
  type ReposPartial,
  type ReviewPartial,
  type ReviewStrictness,
  type SandboxPartial,
  type WebSearchPartial,
  type ThinkingLevel,
} from './schema.ts';

export {
  providerOf,
  resolveConfig,
  type ConfigLayers,
  type ResolvedBackoff,
  type ResolvedConfig,
  type ResolvedCustomProvider,
  type ResolvedMcpServer,
  type ResolvedMode,
  type ResolvedNpmRegistry,
  type ResolvedRateLimit,
  type ResolveOptions,
} from './merge.ts';

export { parseConfigYaml } from './yaml.ts';

export {
  defineCrabdConfig,
  loadCrabdExtension,
  type CrabdExtension,
} from './ts-config.ts';
